#!/usr/bin/env python3
"""Write key.js, the untracked file mathematicat.html unmasks its key from.

This is scraper avoidance, not secrecy: anyone who opens the network tab sees the
key in the Authorization header. Its only job is to keep the provider's key
prefix, and any variable name resembling one, out of the served HTML, since
that is what automated harvesters grep for.

    python3 mask_key.py <key>      # writes key.js
"""
import base64, sys

PASS = "mathematicat"
key = sys.argv[1] if len(sys.argv) > 1 else input("key: ").strip()
masked = base64.b64encode(bytes(c ^ ord(PASS[i % len(PASS)]) for i, c in enumerate(key.encode()))).decode()
open("key.js", "w").write(
    "// Untracked: generated by mask_key.py, never committed. Deploy alongside the page.\n"
    'const KEY_BLOB = "' + masked + '";\n')
print("wrote key.js")
